node {
	notify('Started')
	try{
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 
def directory_terraform= "terraform"

		
stage('GitCheckOut') {
git branch: 'terraform',  url: 'https://github.com/shreya246/devops301.git'
}


stage('Getting Ready for Ansible Deploy'){
   sh "echo \'<h1> TASK BUILD ID: ${env.BUILD_DISPLAY_NAME}</h1>\'  > tomcat/tomcat/files/index.html"
  }




		dir(directory_terraform){
stage('Deployment - Terraform') {
	
sh 'terraform init'
sh 'terraform plan'
sh 'terraform apply --auto-approve'
}
		}
		
	notify("Completed")
	}
	catch(err){
		notify("Error ${err}")
  currentBuild.result = 'FAILURE'
	}

 
}
def notify(status){
    emailext(
    to: "shreyapnseja@gmail.com",
    subject: "${status} :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
    body:"""<p>${status}: :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
            <p>Check Console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}
