node {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 

// Project Dir
    def project_path = "Download"


stage('GitCheckOut') {
git branch: 'stage',  url: 'https://github.com/shreya246/devops301.git'
}



dir(project_path){

stage('Build Managment') {
      def uploadSpec = """{
	 "files": [
	{
	"pattern": "petclinic-war/*.war",
	"target": "files/"
        }
	]
	}"""
	server.upload spec: uploadSpec
 }


stage('Publish build info') {
  server.publishBuildInfo buildInfo
}

	stage('Deployment - Stage'){
deploy adapters: [tomcat8(credentialsId: 'tomcat-credentials', path: '', url: 'http://mueoz30332dns.eastus2.cloudapp.azure.com:8080/')], contextPath: 'petclinic', onFailure: false, war: 'files/petclinic.war'
}
}


 
}
