node {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
	
	notify('Stage started')
	try{
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 

// Project Dir
    def project_path = "Download"


stage('GitCheckOut') {
git branch: 'stage',  url: 'https://github.com/shreya246/devops301.git'
}



dir(project_path){

stage('Build Managment') {
      def uploadSpec = """{
	 "files": [
	{
	"pattern": "petclinic-war/*.war",
	"target": "files/"
        }
	]
	}"""
	server.upload spec: uploadSpec
 }


stage('Publish build info') {
  server.publishBuildInfo buildInfo
}

	stage('Deployment - Stage'){
deploy adapters: [tomcat8(credentialsId: 'tomcat-credentials', path: '', url: 'http://mueoz30332dns.eastus2.cloudapp.azure.com:8080/')], contextPath: 'petclinic', onFailure: false, war: 'files/petclinic.war'
}
}
		notify('Completed')
	}
	catch(err){
		notify('Error ${err}')
		         currentBuild.result = 'FAILURE'
	}

 
}
		       
		       def notify(status){
    emailext(
    to: "shreyapnseja@gmail.com",
    subject: "${status} :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
    body:"""<p>${status}: :JOB '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
            <p>Check Console output at <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a></p>""",
    )
}
