node {
// Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "01"
    def buildInfo = Artifactory.newBuildInfo() 

// Project Dir
    def project_path = "spring-petclinic"


stage('GitCheckOut') {
git branch: 'pre-prod',  url: 'https://github.com/shreya246/devops301.git'
}



dir(project_path){

stage('Maven Clean') {
sh 'mvn clean'
}

stage('Maven Compile') {
sh 'mvn compile'
}

stage('Maven test') {
sh 'mvn test'
}

stage('Maven pkg') {
sh 'mvn package'
}

stage('Build Managment') {
      def uploadSpec = """{
	 "files": [
	{
	"pattern": "**/*.war",
	"target": "petclinic-war"
        }
	]
	}"""
	server.upload spec: uploadSpec
 }


stage('Publish build info') {
  server.publishBuildInfo buildInfo
}
stage("build & SonarQube analysis") {
          
              withSonarQubeEnv('sonar-01') {
                 sh 'mvn  sonar:sonar'
              }
          
      }

stage('Deployment - PreProd') {
sh 'docker-compose up -d --build'
}
	
	
}


 
}
